services:
  postgres:
    image: postgres:latest
    container_name: suggestme-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: suggestme
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d suggestme']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
